CREATE DATABASE loja;

CREATE TABLE products (
  id UUID PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(100),
  price NUMERIC NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE,
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE,
  category_id UUID NOT NULL
);


CREATE TABLE categories (
  id UUID PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE,
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP(0)::TIMESTAMP WITHOUT TIME ZONE
 );
 
 ALTER TABLE products 
 	ADD FOREIGN KEY (category_id) 
    REFERENCES categories (id);